apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment 
spec:   
  replicas: 3
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app

    spec:
      containers:
      - name: db01
        image: mysql:latest
        volumes:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret

      volumes:
      - name: config-volume
        configMap:
          name: db-config

      - name: secret-volume
        secret:
          secretName: my-secret 

        env:
        - name: db_port
          valueFrom:  
            configMapKeyRef:
              name: db-config
              key: db_port

        - name: db_user
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
              
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
