apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: my-app
    key: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      key: front-end
  template:
    metadata:
      labels:
        key: front-end
    spec:
      containers:
      - name: web01
        image: nginx:1.27
        ports:
